const chartTheme = {
   first: {
      confirmed: {
         type: 'confirmed',
         color: '#db2828',
         shadeLight: '#fbedec',
         shadeDark: '#db2828',
         name: 'red',
      },
      active: {
         type: 'active',
         color: '#2185d0',
         shadeLight: '#ecf5fc',
         shadeDark: '#2185d0',
         name: 'blue',
      },
      recovered: {
         type: 'recovered',
         color: '#21ba45',
         shadeLight: '#ecfcf1',
         shadeDark: '#21ba45',
         name: 'green',
      },
      deaths: {
         type: 'deaths',
         color: '#767676',
         shadeLight: '#f4f4f4',
         shadeDark: '#767676',
         name: 'grey',
      },
   },
   second: {
      confirmed: {
         type: 'confirmed',
         color: '#bf00e6',
         shadeLight: '#fbe5ff',
         shadeDark: '#bf00e6',
         name: 'red',
      },
      active: {
         type: 'active',
         color: '#0c5cb3',
         shadeLight: '#ebf4fe',
         shadeDark: '#0c5cb3',
         name: 'blue',
      },
      recovered: {
         type: 'recovered',
         color: '#1b9838',
         shadeLight: '#e9fbee',
         shadeDark: '#1b9838',
         name: 'green',
      },
      deaths: {
         type: 'deaths',
         color: '#ffc21a',
         shadeLight: '#fff8e5',
         shadeDark: '#ffc21a',
         name: 'grey',
      },
   },
   third: {
      confirmed: {
         type: 'confirmed',
         color: '#ff0592',
         shadeLight: '#ffbee3',
         shadeDark: '#ff0592',
         name: 'red',
      },
      active: {
         type: 'active',
         color: '#4d3664',
         shadeLight: '#bab5f6',
         shadeDark: '#4d3664',
         name: 'blue',
      },
      recovered: {
         type: 'recovered',
         color: '#26baee',
         shadeLight: '#9fe8fa',
         shadeDark: '#26baee',
         name: 'green',
      },
      deaths: {
         type: 'deaths',
         color: '#c7004c',
         shadeLight: '#ffaaaa',
         shadeDark: '#c7004c',
         name: 'grey',
      },
   },
   fourth: {
      confirmed: {
         type: 'confirmed',
         color: '#78a40e',
         shadeLight: '#f7fde8',
         shadeDark: '#78a40e',
         name: 'red',
      },
      active: {
         type: 'active',
         color: '#a7490b',
         shadeLight: '#fdf0e7',
         shadeDark: '#a7490b',
         name: 'blue',
      },
      recovered: {
         type: 'recovered',
         color: '#2b5543',
         shadeLight: '#eef6f3',
         shadeDark: '#2b5543',
         name: 'green',
      },
      deaths: {
         type: 'deaths',
         color: '#bb2b79',
         shadeLight: '#faeaf3',
         shadeDark: '#bb2b79',
         name: 'grey',
      },
   },
   fifth: {
      confirmed: {
         type: 'confirmed',
         color: '#4902e3',
         shadeLight: '#eee6ff',
         shadeDark: '#4902e3',
         name: 'red',
      },
      active: {
         type: 'active',
         color: '#db0aae',
         shadeLight: '#fee7f9',
         shadeDark: '#db0aae',
         name: 'blue',
      },
      recovered: {
         type: 'recovered',
         color: '#db0a0a',
         shadeLight: '#fee7e7',
         shadeDark: '#db0a0a',
         name: 'green',
      },
      deaths: {
         type: 'deaths',
         color: '#cddb0a',
         shadeLight: '#fcfee7',
         shadeDark: '#cddb0a',
         name: 'grey',
      },
   },
};

export default chartTheme;
